services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: tasks_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-api:
    build:
      context: ./go-api
    environment:
      DATABASE_URL: postgres://tasks_user:tasks_password@postgres:5432/tasks
      PORT: "8080"
      NATS_URL: nats://nats:4222
      STATS_GRPC_ADDR: rust-worker:50051
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - nats
      - rust-worker

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"

  python-worker:
    build:
      context: ./python-worker
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: postgres://tasks_user:tasks_password@postgres:5432/tasks
      NATS_URL: nats://nats:4222
    depends_on:
      - postgres
      - nats

  rust-worker:
    build:
      context: .
      dockerfile: rust-worker/Dockerfile
    environment:
      NATS_URL: nats://nats:4222
      DATABASE_URL: postgres://tasks_user:tasks_password@postgres:5432/tasks
      GRPC_ADDR: 0.0.0.0:50051
    ports:
      - "50051:50051"
    depends_on:
      - nats
      - postgres

volumes:
  postgres_data:
